service: lambda-place

frameworkVersion: "3"
useDotenv: true
package:
  exclude:
    - .git/**
    - src/**
    - test/**
    - nodemon.json
    - README.md
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs16.x
  architecture: arm64
  stage: '${opt:stage, "dev"}'
  region: us-east-2
  memorySize: 128
  logRetentionInDays: 1

functions:
  api:
    timeout: 36
    handler: dist/lambda.handler
    events:
      - httpApi:
          method: any
          path: /{proxy+}

plugins:
  - serverless-jetpack
  - serverless-offline
