service: lambda-place

frameworkVersion: "3"

package:
  exclude:
    - .git/**
    - src/**
    - test/**
    - nodemon.json
    - README.md
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs16.x
  architecture: arm64
  stage: '${opt:stage, "dev"}'
  region: us-east-2
  memorySize: 128
  logRetentionInDays: 1

functions:
  index:
    memorySize: 256
    timeout: 36
    handler: dist/lambda.handler
    events:
      - http:
          cors: true
          path: "/{proxy+}"
          method: any

plugins:
  - serverless-jetpack
  - serverless-offline
